// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaj_1JGryq2LprW2Nx3JUFd3M5wFyt0J0',
    appId: '1:339458886880:web:b50601848b840ad5d95485',
    messagingSenderId: '339458886880',
    projectId: 'cc-uts',
    authDomain: 'cc-uts.firebaseapp.com',
    storageBucket: 'cc-uts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSbPHFhzz8KwqknkAPb8oe1GO5yPBVMs',
    appId: '1:339458886880:android:0b1b61bc255f7b1ed95485',
    messagingSenderId: '339458886880',
    projectId: 'cc-uts',
    storageBucket: 'cc-uts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZiYgAGNkTmw4idKGS2fGcUAVp79J3q4',
    appId: '1:339458886880:ios:ea84dec2bce70959d95485',
    messagingSenderId: '339458886880',
    projectId: 'cc-uts',
    storageBucket: 'cc-uts.firebasestorage.app',
    iosBundleId: 'com.CC-UTS',
  );
}
